[package]
name = "neora-protocol-generator"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = ""

[dependencies]
neora-scanner = { path = "../neora-scanner" }
heck = "0.5.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"

